%YAML 1.1
## rblib project.yaml
##
## Known limitations for this project.yaml syntax:
## - do not delimit values with a tab character, as this may fail in psych under jruby
---
## common gemspec author info
authors:
  - Sean Champ
email:
  - spchamp@users.noreply.github.com
## default version when not specified in gem scope
version: 1.0.1
## default licenses list
licenses:
  - MPL-2.0
## common docs files, used in each gem
docs:
  - README.md
  - COPYING.md
## common development dependencies
devo_depends:
  ## common development dependencies for all project gemspecs,
  ## to be published with each gemspec.
  ##
  ## gems for any tool dependencies may be configured in the project Gemfile,
  ## e.g irb, pry, or in the optional, non-version-controlled Gemfile.local
  ##
  ## Usage note: always quote the version-bounds strings when using any version-bounded
  ## syntax for dependencies in project.yaml
  - [rbs, ">=2"]
  - [rake, ">=13"]
  - [rspec, ">=3"]
  - [debug, ">=1"]
  - [yard, ">=0.9"]
  ## bundler can install the latest version of bundler,
  ## which may be needed for resolving built-in gems with
  ## newer Ruby 3.1 releases (e.g for the psych dep)
  - [bundler, ">= 2.3"]
required_ruby_version: ">= 2.7.0"
require_paths:
  - lib
publish_gems:
  - pebbl_app-support
#  - pebbl_app-gtk_support
gems:
  pebbl_app-support:
    modules:
      - PebblApp::Project
      - PebblApp::Support
    summary: PebblApp support for projects
    description:
      Ruby toolkit for PebblApp projects
    source_files:
      - lib/pebbl_app.rb
      - lib/pebbl_app/app.rb
      - lib/pebbl_app/app_log.rb
      - lib/pebbl_app/app_mixin.rb
      - lib/pebbl_app/attr_proxy.rb
      - lib/pebbl_app/conf.rb
      - lib/pebbl_app/const.rb
      - lib/pebbl_app/exceptions.rb
      - lib/pebbl_app/files.rb
      - lib/pebbl_app/file_manager.rb
      - lib/pebbl_app/framework.rb
      - lib/pebbl_app/freeze_util.rb
      - lib/pebbl_app/logger_mixin.rb
      - lib/pebbl_app/project_module.rb
      - lib/pebbl_app/shell.rb
      - lib/pebbl_app/project/spec_finder.rb ## ?? see conf. patch & remove refs
      - lib/pebbl_app/y_spec.rb
    # sandbox_files:
    #   ## not published with the gem - FIXME unmaintained prototypes
    #   - lib/pebbl_app/project/sandbox.rb
    #   - lib/pebbl_app/project/sandbox/spectool.rb
    #   - sandbox/lib/pebbl_app/project/ext_spec.rb
    depends:
      - psych

  pebbl_app-gtk_support:
    modules:
      - PebblApp::GtkSupport
    summary: PebblApp support for Ruby-GNOME applications
    description:
      A minial Ruby toolkit for PebblApp applications using Ruby-GNOME
    build_depends:
      - [pebbl_app-support, ">=1"]
    depends:
      - [pastel, ">=0.8"]
      - gtk3:
          ## testing the hash/map decoder in YSpec & adding the dep
          versions: ">=3.5.2"
      - [pebbl_app-support, ">=1.0"]
    source_files:
      - lib/pebbl_app/accel_mixin.rb
      - lib/pebbl_app/gactionable.rb
      - lib/pebbl_app/gapp_mixin.rb
      - lib/pebbl_app/gapp.rb
      - lib/pebbl_app/gmain.rb
      - lib/pebbl_app/gobj_type.rb
      - lib/pebbl_app/gtk_app.rb
      - lib/pebbl_app/gtk_builders.rb
      - lib/pebbl_app/gtk_conf.rb
      - lib/pebbl_app/gtk_framework.rb
      - lib/pebbl_app/keysym.rb
      - lib/pebbl_app/tree_util.rb
      ## merged with upwards module
      #- lib/pebbal_app/gtk_framework/exceptions.rb
      ## earlier prototype definitions:
      - lib/pebbl_app/gtk_framework/threads.rb
      - lib/pebbl_app/gtk_framework/sysexit.rb
      - lib/pebbl_app/gbuilder_app.rb
      ## sandbox
      #- lib/pebbl_app/gtk_framework/basedir.rb
      - sandbox/service-example.rb

  vty:
    summary: Vty is a desktop terminal emulator using Ruby-GNOME
    description:
      Vty is a desktop terminal emulator using GNOME Vte3 and Ruby-GNOME.
    deps:
      - [vte3, ">= 3.5.2"]
      - pebbl_app-gtk_support
    source_files:
      - lib/vty.rb
      - ui/appwindow.vty.ui
      - ui/prefs.vty.ui

  riview:
    modules:
      - RIView
    summary: Documentation browser for Ruby, using Ruby-GNOME (prototype)
    description:
      Prototype for a documentation browser in Ruby, using Ruby-GNOME
    build_depends:
      - pebbl_app-support
    depends:
      - [gtk3, ">=3"]
      - pebbl_app-gtk_support
      - rikit
      - pebbl_app-support
    source_files:
      - lib/riview.rb
      - lib/riview/dataproxy.rb
      - lib/riview/riview_app.rb
    resource_files:
      - ui/appwindow.riview.ui
      - ui/prefs.riview.ui
      - ui/docview.riview.ui

  rikit:
    modules:
      - RIKit
    summary: Prototype for user documentation support for Ruby
    description:
      Prototype for user documentation support for Ruby, using rdoc
    build_depends:
      - pebbl_app-support
    depends:
      - rdoc
      - pebbl_app-support

  ### sandbox - source code needs migration to root project context
  # projectkit:
  #   module: ProjectKit
  #   summary: Prototype for project tooling support
  #   description:
  #     This project's single source file will likely be migtrated into
  #     the pebbl_app-support gemspec
  #   build_depends:
  #     - pebbl_app-support
  #   depends:
  #     - pebbl_app-support
  #   source_files:
  #     - lib/projectkit/rspectool.rb
