%YAML 1.1
## rblib project.yaml
##
## Known limitations for this project.yaml syntax:
## - do not delimit values with a tab character, as this may fail in psych under jruby
---
## common gemspec author, contact info
authors:
  - Sean Champ
email:
  - spchamp@users.noreply.github.com
## default version when not specified in gem scope
version: 1.0.1
## default licenses list
licenses:
  - MPL-2.0
## common docs files, used in each gem
docs:
  - README.md
  - COPYING.md
## common spec files for rpsec tests
spec_files:
  - spec/spec_helper.rb
  - spec/spec_helper_spec.rb
## common development dependencies
devo_depends:
  ## common development dependencies for all project gemspecs,
  ## to be published with each gemspec.
  ##
  ## gems for any tool dependencies may be configured in the project Gemfile,
  ## e.g irb, pry, or in the optional, non-version-controlled Gemfile.local
  ##
  ## Usage note: always quote the version-bounds strings when using any version-bounded
  ## syntax for dependencies in project.yaml
  - [rbs, ">=2"]
  - [rake, ">=13"]
  - [rspec, ">=3"]
  - [debug, ">=1"]
  - [yard, ">=0.9"]
  ## bundler can install the latest version of bundler,
  ## which may be needed for resolving built-in gems with
  ## newer Ruby 3.1 releases
  - [bundler, ">= 2.3"]
required_ruby_version: ">= 2.7.0"
require_paths:
  - lib
publish_gems:
  - pebbl_app-support
#  - pebbl_app-gtk_support
gems:
  pebbl_app-support:
    modules:
      - PebblApp::Project
      - PebblApp::Support
    summary: PebblApp support for projects
    description:
      A minimal Ruby toolkit for PebblApp projects
    source_files:
      - lib/pebbl_app.rb
      - lib/pebbl_app/project.rb
      - lib/pebbl_app/project/project_module.rb
      - lib/pebbl_app/project/spec_finder.rb
      - lib/pebbl_app/project/y_spec.rb
      - lib/pebbl_app/support.rb
      - lib/pebbl_app/support/app.rb
      - lib/pebbl_app/support/app_prototype.rb
      - lib/pebbl_app/support/config.rb
      - lib/pebbl_app/support/const.rb
      - lib/pebbl_app/support/exceptions.rb
      - lib/pebbl_app/support/file_manager.rb
      - lib/pebbl_app/support/files.rb
      - lib/pebbl_app/support/sh_proc.rb
    sandbox_files:
      ## not published with the gem. To define autoloads for these files e.g:
      ##    require 'thinkum_space/project'
      ## as conditionally under 'bundle exec <ruby>' in the rblib source tree
      ##
      ## FIXME this should probably be moved to a root 'sandbox' library
      ## path, then activated with some top-level add-on parameter for
      ## bundler (or when :development under bundler eg), beyond an ad
      ## hoc dispatch and test onto a bundler environment variable.
      - lib/pebbl_app/project/sandbox.rb
      - lib/pebbl_app/project/sandbox/spectool.rb
      - sandbox/lib/pebbl_app/project/ext_spec.rb
    depends:
## TBD add an internal_depends field for information purposes vis "built-in gems?"
#      - psych

  pebbl_app-gtk_support:
    module: PebblApp::GtkSupport
    summary: PebblApp support for Ruby-GNOME applications
    description:
      A minial Ruby toolkit for PebblApp applications using Ruby-GNOME
    build_depends:
      - pebbl_app-support
    depends:
      - [gtk3, ">=3"]
      - pebbl_app-support
    source_files:
      - lib/pebbl_app/gtk_support.rb
      - lib/pebbl_app/gtk_support/gtk_app_prototype.rb
      - lib/pebbl_app/gtk_support/gtk_config.rb
      - lib/pebbl_app/gtk_support/exceptions.rb
      ## earlier prototype definitions:
      - lib/pebbl_app/gtk_support/logging.rb
      - lib/pebbl_app/gtk_support/threads.rb
      - lib/pebbl_app/gtk_support/sysexit.rb
      - lib/pebbl_app/gtk_support/glib_type_ext.rb
      - lib/pebbl_app/gtk_support/gtk_type_ext.rb
      - lib/pebbl_app/gtk_support/gbuilder_app.rb
      - lib/pebbl_app/gtk_support/basedir.rb
      ### sandbox (to implement)
      ## - lib/pebbl_app/gtk_support/tools/resources.rb
      ## - lib/pebbl_app/gtk_support/tools/ui.rb
      ## - lib/pebbl_app/gtk_support/tools/schemas.rb

  riview:
    module: RIView
    summary: Documentation browser for Ruby, using Ruby-GNOME (prototype)
    description:
      This is a project.
    build_depends:
      - pebbl_app-support
    depends:
      - [gtk3, ">=3"]
      - pebbl_app-gtk_support
      - rikit
      - pebbl_app-support
    source_files:
      - lib/riview.rb
      - lib/riview/dataproxy.rb
      - lib/riview/riview_app.rb
    resource_files:
      - ui/appwindow.riview.ui
      - ui/prefs.riview.ui
      - ui/docview.riview.ui

  rikit:
    module: RIKit
    summary: Prototype for user documentation support for Ruby
    description:
      This is a project.
    build_depends:
      - pebbl_app-support
    depends:
      - rdoc
      - pebbl_app-support

  ### sandbox - source code needs migration to root project context
  # projectkit:
  #   module: ProjectKit
  #   summary: Prototype for project tooling support
  #   description:
  #     This project's single source file will likely be migtrated into
  #     the pebbl_app-support gemspec
  #   build_depends:
  #     - pebbl_app-support
  #   depends:
  #     - pebbl_app-support
  #   source_files:
  #     - lib/projectkit/rspectool.rb
