## rblib project.yaml
---
authors:
  - Sean Champ
email:
  - spchamp@users.noreply.github.com
version: 1.0.2
licenses:
  - MPL-2.0
devo_depends:
  - psych
  - rbs
  - rake
  - rspec
  - standard
  - debug
required_ruby_version: ">= 2.7.0"
require_paths:
  - lib
gems:
  thinkum_space-project:
    module: ThinkumSpace::Project
    summary: Project Tools
    description: Project tooling
    source_files:
      - lib/thinkum_space.rb
      - lib/thinkum_space/project.rb
      - lib/thinkum_space/project/ruby.rb
      - lib/thinkum_space/project/ruby/y_spec.rb
      - lib/thinkum_space/project/ruby/spectool.rb

  riview:
    module: RIView
    summary: Documentation browser for Ruby, using Ruby-GNOME (prototype)
    description:
      This is a project.
    depends:
      - gtk3
      - gappkit
      - rikit
    resource_files:
      - ui/appwindow.glade
      - ui/prefs.ui
      - ui/docview.ui

  gappkit:
    module: GAppKit
    summary: Application support for Ruby-GNOME
    description:
      This is a project.
    depends:
      - gtk3

  rikit:
    module: RIKit
    summary: Prototype for user documentation support for Ruby
    description:
      This is a project.
    depends:
      - rdoc
