%YAML 1.1
## rblib project.yaml
---
authors:
  - Sean Champ
email:
  - spchamp@users.noreply.github.com
version: 1.0.4
licenses:
  - MPL-2.0
docs:
  - README.md
  - COPYING.md
devo_depends:
  ## NB always quote the version-bounds strings when using any version-bounded
  ## syntax for dependencies in project.yaml
  - [rbs,	">=2"]
  - [rake,	">=13"]
  - [rspec,	">=3"]
  - [debug,	">=1"]
  - [irb,	">=1"]
  - [yard,	">=0.9"]
required_ruby_version: ">= 2.7.0"
require_paths:
  - lib
publish_gems:
  - thinkum_space-project
gems:
  thinkum_space-project:
    module: ThinkumSpace::Project
    summary: Project Tooling
    description:
      This gem provides a reusable toolbox for project configuration
      methods used in Ruby projects at Thinkum.Space.
    source_files:
      - lib/thinkum_space.rb
      - lib/thinkum_space/project.rb
      - lib/thinkum_space/project/project_module.rb
      - lib/thinkum_space/project/y_spec.rb
    sandbox_files:
      ## not published with the gem. To define autoloads for these files e.g:
      ##    require 'thinkum_space/project'
      ## as conditionally under 'bundle exec <ruby>' in the rblib source tree
      ##
      ## FIXME this should probably be moved to a root 'sandbox' library
      ## path, then activated with some top-level add-on parameter for
      ## bundler (or when :development under bundler eg), beyond an ad
      ## hoc dispatch and test onto a bundler environment variable.
      - lib/thinkum_space/project/sandbox.rb
      - lib/thinkum_space/project/sandbox/spectool.rb
    depends:
      - psych

  riview:
    module: RIView
    summary: Documentation browser for Ruby, using Ruby-GNOME (prototype)
    description:
      This is a project.
    build_depends:
      - thinkum_space-project
    depends:
      - [gtk3, ">=3"]
      - g_app-support
      - rikit
      - thinkum_space-project
    source_files:
      - lib/riview.rb
      - lib/riview/dataproxy.rb
      - lib/riview/riview_app.rb
    resource_files:
      - ui/appwindow.riview.ui
      - ui/prefs.riview.ui
      - ui/docview.riview.ui

  g_app-support:
    module: GApp::Support
    autoloads:
      - GApp: lib/g_app.rb
      - GApp::Support: lib/g_app/support.rb
    summary: Application support for Ruby-GNOME applications (prototype)
    description:
      The g_app-support gem provides a small number of reusable Ruby
      module and class definitions for applications using Ruby-GNOME
    build_depends:
      - thinkum_space-project
    depends:
      - [gtk3, ">=3"]
      - thinkum_space-project
    source_files:
      - lib/g_app/support.rb
      - lib/g_app/support/logging.rb
      - lib/g_app/support/threads.rb
      - lib/g_app/support/sysexit.rb
      - lib/g_app/support/glib_type_ext.rb
      - lib/g_app/support/gtk_type_ext.rb
      - lib/g_app/support/gbuilder_app.rb
      - lib/g_app/support/basedir.rb
##    - lib/g_app/support/tools/resources.rb
##    - lib/g_app/support/tools/ui.rb
##    - lib/g_app/support/tools/schemas.rb

  rikit:
    module: RIKit
    summary: Prototype for user documentation support for Ruby
    description:
      This is a project.
    build_depends:
      - thinkum_space-project
    depends:
      - rdoc
      - thinkum_space-project

  ### sandbox - source code needs migration to root project context
  # projectkit:
  #   module: ProjectKit
  #   summary: Prototype for project tooling support
  #   description:
  #     This project's single source file will likely be migtrated into
  #     the thinkum_space-project gemspec
  #   build_depends:
  #     - thinkum_space-project
  #   depends:
  #     - thinkum_space-project
  #   source_files:
  #     - lib/projectkit/rspectool.rb
