name: Ruby

## docs e.g
## https://github.com/ruby/setup-ruby

## to view the latest log, assuming the gh CLI is installed and configured
## and running in a working tree for this project:
##
# $ gh run view --log $(gh run list --json databaseId | awk 'BEGIN { RS="},?"; FS=":" } { print $2; exit 1 }')
##

env:
#  RUBYOPT: '--debug'
  ACTIONS_RUNNER_DEBUG: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs:
      post: find /home/runner/work/${{ github.repository_owner }}//${{ github.repository }}/vendor/bundle/ -type f -name mkmf.log | { while read LOG; do echo "#-- ${LOG}"; cat ${LOG}; done; }
      post-if: job.status == 'failure'
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', head, jruby, jruby-head, truffleruby, truffleruby-head]

    steps:
    - name: Disable initramfs update
      run: sudo sed -i.bak 's@yes@no@g' /etc/initramfs-tools/update-initramfs.conf
    - name: Disable man-db update
      run: sudo rm -f /var/lib/man-db/auto-update
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
